version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ventas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - spring-network

volumes:
  postgres_data:
    driver: local

networks:
  spring-network:
    driver: bridge
